[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "erc20/=../MyFirstERC20Token(MLPT)/"
]
solc = "0.8.30"


[fmt]
line_length = 250
tab_width = 4
bracket_spacing = false
int_types = "long"
quote_style = "double"
number_underscore = "thousands"
wrap_comments = true
single_line_statement_blocks = "single"

[profile.zksync]
src = "src"
libs = ["lib"]
fallback_oz = true
mode = "3"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
